config/routes.rb
Draryi::Application.routes.draw do
  resources :activities

  resources :programs

  resources :providers

  get "pages/activity"

  get "pages/program"

  get "pages/report"

  get "pages/event"

  mount Surveyor::Engine => "/surveys", :as => "surveyor"

   root :to => 'pages#index'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  attr_accessible :name, :program_id
end

app/models/program.rb
class Program < ActiveRecord::Base
  attr_accessible :name, :provider_id
end

app/models/provider.rb
class Provider < ActiveRecord::Base
  attr_accessible :name
end

app/models/survey.rb.rb
class Survey < ActiveRecord::Base
      include Surveyor::Models::SurveyMethods
      def title
        "Custom #{super}"
      end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @activities }
    end
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
    @activity = Activity.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/new
  # GET /activities/new.json
  def new
    @activity = Activity.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/1/edit
  def edit
    @activity = Activity.find(params[:id])
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(params[:activity])

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render json: @activity, status: :created, location: @activity }
      else
        format.html { render action: "new" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /activities/1
  # PUT /activities/1.json
  def update
    @activity = Activity.find(params[:id])

    respond_to do |format|
      if @activity.update_attributes(params[:activity])
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to activities_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def activity
  end

  def program
  end

  def report
  end

  def event
  end

  def index
  end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  # GET /programs
  # GET /programs.json
  def index
    @programs = Program.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @programs }
    end
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
    @program = Program.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @program }
    end
  end

  # GET /programs/new
  # GET /programs/new.json
  def new
    @program = Program.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @program }
    end
  end

  # GET /programs/1/edit
  def edit
    @program = Program.find(params[:id])
  end

  # POST /programs
  # POST /programs.json
  def create
    @program = Program.new(params[:program])

    respond_to do |format|
      if @program.save
        format.html { redirect_to @program, notice: 'Program was successfully created.' }
        format.json { render json: @program, status: :created, location: @program }
      else
        format.html { render action: "new" }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /programs/1
  # PUT /programs/1.json
  def update
    @program = Program.find(params[:id])

    respond_to do |format|
      if @program.update_attributes(params[:program])
        format.html { redirect_to @program, notice: 'Program was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program = Program.find(params[:id])
    @program.destroy

    respond_to do |format|
      format.html { redirect_to programs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  # GET /providers
  # GET /providers.json
  def index
    @providers = Provider.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @providers }
    end
  end

  # GET /providers/1
  # GET /providers/1.json
  def show
    @provider = Provider.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @provider }
    end
  end

  # GET /providers/new
  # GET /providers/new.json
  def new
    @provider = Provider.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @provider }
    end
  end

  # GET /providers/1/edit
  def edit
    @provider = Provider.find(params[:id])
  end

  # POST /providers
  # POST /providers.json
  def create
    @provider = Provider.new(params[:provider])

    respond_to do |format|
      if @provider.save
        format.html { redirect_to @provider, notice: 'Provider was successfully created.' }
        format.json { render json: @provider, status: :created, location: @provider }
      else
        format.html { render action: "new" }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /providers/1
  # PUT /providers/1.json
  def update
    @provider = Provider.find(params[:id])

    respond_to do |format|
      if @provider.update_attributes(params[:provider])
        format.html { redirect_to @provider, notice: 'Provider was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /providers/1
  # DELETE /providers/1.json
  def destroy
    @provider = Provider.find(params[:id])
    @provider.destroy

    respond_to do |format|
      format.html { redirect_to providers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/surveyor_controller.rb
# encoding: UTF-8
module SurveyorControllerCustomMethods
  def self.included(base)
    # base.send :before_filter, :require_user   # AuthLogic
    # base.send :before_filter, :login_required  # Restful Authentication
    base.send :layout, 'application'

  end

  # Actions
  def new
    super
    # @title = "You can take these surveys"
  end
  def create
    super
  end
  def show
    super
  end
  def edit
    super
  end
  def update
    super
  end

  # Paths
  def surveyor_index
    # most of the above actions redirect to this method
    super # surveyor.available_surveys_path
  end
  def surveyor_finish
    # the update action redirects to this method if given params[:finish]
    super # surveyor.available_surveys_path
  end
end
class SurveyorController < ApplicationController
  include Surveyor::SurveyorControllerMethods
  include SurveyorControllerCustomMethods
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :program_id %><br />
    <%= f.number_field :program_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<h1>Listing activities</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Program</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @activities.each do |activity| %>
  <tr>
    <td><%= activity.name %></td>
    <td><%= activity.program_id %></td>
    <td><%= link_to 'Show', activity %></td>
    <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
    <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<h1>New activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @activity.name %>
</p>

<p>
  <b>Program:</b>
  <%= @activity.program_id %>
</p>


<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>

app/views/layouts/application.html.erb
<html >
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
      
      <%= stylesheet_link_tag    "application", :media => "all" %>
  	<%= javascript_include_tag "application" %>
  		<%= csrf_meta_tags %>

    <title>Alerta Joven</title>

    <!-- Custom styles for this template -->
      <link href="assets/sticky-footer-navbar.css" rel="stylesheet">
      <link href="assets/bootstrap.min.css" rel="stylesheet">
  </head>

  <body>

    <!-- Wrap all page content here -->
    <div id="wrap">

      <!-- Fixed navbar -->
      <div class="navbar navbar-fixed-top">
        <div class="container">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Alerta Joven</a>
          <div class="nav-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="active"><a href="/">Home</a></li>
              <li><%= link_to 'Providers', providers_path %></li>
              <li><%= link_to 'Programs', programs_path %></li>
              <li><%= link_to 'Activities', activities_path %></li>
               <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Reports <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Particiapnt Coverage</a></li>
                  <li><a href="#">Provider Coverage</a></li>
                  <li><a href="#">Activity Utilization</a></li>
                  <li><a href="#">Event Summary</a></li>
                  <li><a href="#">Program Detail</a></li>
                </ul>
              </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>

      <!-- Begin page content -->
      <div class="container footer-padding" >

		<%= yield %>

      
      </div>

    <div id="footer">
      <div class="container">
       
       Alerta Joven &copy; 2013. This website was made possible by blah, blah, blah

      </div>
    </div>

   

  </body>
</html>

app/views/layouts/surveyor_custom.html.erb
# encoding: UTF-8
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>Survey: <%= controller.action_name %></title>
  <%= surveyor_includes %>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/pages/activity.html.erb
<div class="page-header">
  <h1>Activity</h1>
</div>

app/views/pages/event.html.erb
<div class="page-header">
  <h1>Events</h1>
</div>

app/views/pages/index.html.erb
 <div class="alert">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <strong>Warning!</strong> Your program exceeds %110 capacity/quota
        </div>

          <div class="page-header">
        <h1>Dominican Repulic At Risk Youth Initiative <small>Subtext for header</small></h1>
      </div>

        <div class="panel"style="float: left; margin: 20px">
          <div class="panel-heading">
          <h3 class="panel-title">Forms</h3>
        </div>
         <p> <%= link_to 'Participant Registrion Form', 'surveys/participant-registration',:method => :post %> </a></p>
         <p>Participant Exit Survey</p>
         <p>Program Survey</p>
      </div>

        <div class="panel" style="float: left; margin: 20px">
          <div class="panel-heading">
          <h3 class="panel-title">Reports</h3>
        </div>
         <p>Participant Survey</p>
         <p>Participant Exit Survey</p>
         <p>Program Survey</p>
      </div>

      <div class="panel" style="float: left; margin: 20px">
          <div class="panel-heading">
          <h3 class="panel-title">Admin</h3>
        </div>
         <p>Manage Activities</p>
         <p>Manage Events</p>
      </div>


<div style="float: left">
      
    <div style="margin: 20px; width: 150px" >
      <h1 style="font-family: league-gothic-1,league-gothic-2,sans-serif; font-size: 6em; text-align: center">21</h1>
      <p>Contacts to Execute
    </div>
      
      <div style="margin: 20px">
          <h4>
          Upcoming Events
          </h4>
         <p>Event Tomorrow</p>
         <p>Event Next Week</p>
      </div>
</div>
      
      </div>

app/views/pages/program.html.erb
<div class="page-header">
  <h1>Programs </h1>
</div>

app/views/pages/report.html.erb
<div class="page-header">
  <h1>Reports </h1>
</div>

app/views/programs/_form.html.erb
<%= form_for(@program) do |f| %>
  <% if @program.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@program.errors.count, "error") %> prohibited this program from being saved:</h2>

      <ul>
      <% @program.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :provider_id %><br />
    <%= f.number_field :provider_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/programs/edit.html.erb
<h1>Editing program</h1>

<%= render 'form' %>

<%= link_to 'Show', @program %> |
<%= link_to 'Back', programs_path %>

app/views/programs/index.html.erb
<h1>Listing programs</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Provider</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @programs.each do |program| %>
  <tr>
    <td><%= program.name %></td>
    <td><%= program.provider_id %></td>
    <td><%= link_to 'Show', program %></td>
    <td><%= link_to 'Edit', edit_program_path(program) %></td>
    <td><%= link_to 'Destroy', program, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Program', new_program_path %>

app/views/programs/new.html.erb
<h1>New program</h1>

<%= render 'form' %>

<%= link_to 'Back', programs_path %>

app/views/programs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @program.name %>
</p>

<p>
  <b>Provider:</b>
  <%= @program.provider_id %>
</p>


<%= link_to 'Edit', edit_program_path(@program) %> |
<%= link_to 'Back', programs_path %>

app/views/providers/_form.html.erb
<%= form_for(@provider) do |f| %>
  <% if @provider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@provider.errors.count, "error") %> prohibited this provider from being saved:</h2>

      <ul>
      <% @provider.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/providers/edit.html.erb
<h1>Editing provider</h1>

<%= render 'form' %>

<%= link_to 'Show', @provider %> |
<%= link_to 'Back', providers_path %>

app/views/providers/index.html.erb
<h1>Listing providers</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @providers.each do |provider| %>
  <tr>
    <td><%= provider.name %></td>
    <td><%= link_to 'Show', provider %></td>
    <td><%= link_to 'Edit', edit_provider_path(provider) %></td>
    <td><%= link_to 'Destroy', provider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Provider', new_provider_path %>

app/views/providers/new.html.erb
<h1>New provider</h1>

<%= render 'form' %>

<%= link_to 'Back', providers_path %>

app/views/providers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @provider.name %>
</p>


<%= link_to 'Edit', edit_provider_path(@provider) %> |
<%= link_to 'Back', providers_path %>